"""
SSTV PD120 Decoder Python Bindings (C++23)
"""
from __future__ import annotations
import collections.abc
import numpy
import numpy.typing
import typing
__all__: list[str] = ['Decoder', 'Pixel', 'SSTVFamily', 'SSTVMode']
class Decoder:
    def __init__(self, sample_rate: typing.SupportsFloat) -> None:
        ...
    def process(self, samples: typing.Annotated[numpy.typing.ArrayLike, numpy.float32]) -> None:
        """
        Process audio samples (NumPy array)
        """
    def reset(self) -> None:
        ...
    def set_on_image_complete_callback(self, arg0: collections.abc.Callable[[typing.SupportsInt, typing.SupportsInt], None]) -> None:
        ...
    def set_on_line_decoded_callback(self, arg0: collections.abc.Callable[[typing.SupportsInt, collections.abc.Sequence[Pixel]], None]) -> None:
        ...
    def set_on_mode_detected_callback(self, arg0: collections.abc.Callable[[SSTVMode], None]) -> None:
        ...
class Pixel:
    def __init__(self, arg0: typing.SupportsInt, arg1: typing.SupportsInt, arg2: typing.SupportsInt) -> None:
        ...
    def __repr__(self) -> str:
        ...
    @property
    def b(self) -> int:
        ...
    @b.setter
    def b(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def g(self) -> int:
        ...
    @g.setter
    def g(self, arg0: typing.SupportsInt) -> None:
        ...
    @property
    def r(self) -> int:
        ...
    @r.setter
    def r(self, arg0: typing.SupportsInt) -> None:
        ...
class SSTVFamily:
    """
    Members:
    
      PD
    
      UNKNOWN
    """
    PD: typing.ClassVar[SSTVFamily]  # value = <SSTVFamily.PD: 0>
    UNKNOWN: typing.ClassVar[SSTVFamily]  # value = <SSTVFamily.UNKNOWN: 1>
    __members__: typing.ClassVar[dict[str, SSTVFamily]]  # value = {'PD': <SSTVFamily.PD: 0>, 'UNKNOWN': <SSTVFamily.UNKNOWN: 1>}
    def __eq__(self, other: typing.Any) -> bool:
        ...
    def __getstate__(self) -> int:
        ...
    def __hash__(self) -> int:
        ...
    def __index__(self) -> int:
        ...
    def __init__(self, value: typing.SupportsInt) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __ne__(self, other: typing.Any) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __setstate__(self, state: typing.SupportsInt) -> None:
        ...
    def __str__(self) -> str:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def value(self) -> int:
        ...
class SSTVMode:
    @property
    def duration_s(self) -> float:
        ...
    @property
    def family(self) -> SSTVFamily:
        ...
    @property
    def height(self) -> int:
        ...
    @property
    def name(self) -> str:
        ...
    @property
    def vis_code(self) -> int:
        ...
    @property
    def width(self) -> int:
        ...
